# Generated by Django 6.1.1 on 2026-09-02 17:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeocodeCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=512, unique=True)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lon', models.FloatField(blank=True, null=True)),
                ('display_name', models.CharField(blank=True, default='', max_length=512)),
                ('city', models.CharField(blank=True, default='', max_length=255)),
                ('state', models.CharField(blank=True, default='', max_length=255)),
                ('found', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_location', models.CharField(max_length=512)),
                ('pickup_location', models.CharField(max_length=512)),
                ('dropoff_location', models.CharField(max_length=512)),
                ('current_cycle_used', models.FloatField()),
                ('start_date', models.DateField(blank=True, null=True)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('start_datetime', models.DateTimeField(blank=True, null=True)),
                ('home_terminal_timezone', models.CharField(default='America/Chicago', max_length=64)),
                ('assumed_start_time', models.BooleanField(default=True)),
                ('driver_name', models.CharField(blank=True, default='', max_length=255)),
                ('carrier_name', models.CharField(blank=True, default='', max_length=255)),
                ('truck_number', models.CharField(blank=True, default='', max_length=128)),
                ('trailer_number', models.CharField(blank=True, default='', max_length=128)),
                ('main_office', models.CharField(blank=True, default='', max_length=512)),
                ('co_driver', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance_miles', models.FloatField()),
                ('duration_hours', models.FloatField()),
                ('geometry', models.JSONField(default=list)),
                ('legs', models.JSONField(default=list)),
                ('provider', models.CharField(default='OSRM', max_length=64)),
                ('trip', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='route', to='trips.trip')),
            ],
        ),
        migrations.CreateModel(
            name='ScheduledActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seq', models.PositiveIntegerField()),
                ('activity_type', models.CharField(max_length=32)),
                ('duty_status', models.CharField(max_length=32)),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('duration_minutes', models.FloatField()),
                ('distance_miles', models.FloatField(default=0.0)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lon', models.FloatField(blank=True, null=True)),
                ('location_name', models.CharField(blank=True, default='', max_length=512)),
                ('note', models.CharField(blank=True, default='', max_length=512)),
                ('leg_index', models.IntegerField(default=-1)),
                ('miles_into_leg', models.FloatField(default=0.0)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='trips.trip')),
            ],
            options={
                'ordering': ['seq'],
                'unique_together': {('trip', 'seq')},
            },
        ),
        migrations.CreateModel(
            name='DailyLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('day_number', models.PositiveIntegerField()),
                ('off_duty_hours', models.FloatField(default=0.0)),
                ('sleeper_hours', models.FloatField(default=0.0)),
                ('driving_hours', models.FloatField(default=0.0)),
                ('on_duty_hours', models.FloatField(default=0.0)),
                ('miles', models.FloatField(default=0.0)),
                ('remarks', models.JSONField(default=list)),
                ('rendered_file', models.CharField(blank=True, default='', max_length=512)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_logs', to='trips.trip')),
            ],
            options={
                'ordering': ['day_number'],
                'unique_together': {('trip', 'day_number')},
            },
        ),
    ]
